stages:
  - test
  - publish

test:
  stage: test
  image: node:lts
  except:
    - schedules
  before_script:
    - yarn install
  script:
    - yarn lint
    - yarn test
  coverage: '/Lines\s*:\s*(\d*\.?\d+)%/'
  artifacts:
    when: always
    paths:
      - coverage
      - jest-stare
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/

audit:
  stage: test
  image: node:lts
  before_script:
    - yarn install
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
  script:
    - yarn audit

publish:
  stage: publish
  image: node:lts
  before_script:
    - yarn install
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - node_modules/
  script:
    - yarn bundle
  artifacts:
    paths:
      - dist/spake2.min.js
    name: 'spake2.min.js'